version: '3'

services:

  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '80:8080'
    links:
      - phpfpm
    volumes:
      - ./logs/access.log:/opt/bitnami/nginx/logs/myapp-access.log
      - ./logs/error.log:/opt/bitnami/nginx/logs/myapp-error.log
      - ./nginx/app.conf:/bitnami/nginx/conf/vhosts/app.conf
      - ./public:/myapps
    command:
      - service nginx start


  phpfpm:
    image: 'bitnami/php-fpm'
    ports:
      - '9000:9000'
    volumes:
      - ./public:/myapps


  mysql:
    image: 'mysql:5.7'
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=M@f123

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8080:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: M@f123
        PMA_HOST: mysql
