version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    links:
      - phpfpm
    volumes:
      - ./logs/access.log:/opt/logs/myapp-access.log
      - ./logs/error.log:/opt/logs/myapp-error.log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/myapps

  phpfpm:
    image: 'bitnami/php-fpm'
    ports:
      - '9000:9000'
    volumes:
      - ./public:/myapps


  mysql:
    image: 'mysql:5.7'
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=M@f123

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8080:80'
    links:
        - mysql:mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: M@f123
        PMA_HOST: mysql
